# The basics and learning as a newbie ### 

## The Knight Class
In KAG, the are 3 main classes: the Archer, the Builder and the Knight. The knight is arguably the strongest class of the game. A good team in CTF (the most played gamemode -- Capture The Flag) or TTH (Take The Halls) should be mostly composed of knights protecting the builders and archers. In TDM (team deathmatch) the knight is the most played class as well.

As a knight in CTF and TTH, your role is helping the team advance forward to get the enemy flag/enemy hall, but before you can learn more about gamemodes and playing in a team, let’s talk about the combat mechanics first.

## Mechanics
As a knight, you can use your sword and shield to do the following stuff:

**Jab** -- the simplest attack. It does 1 heart of damage.

[gif 1 -- jabbing someone]

**Slash** -- charged attack (it takes half a second to charge it -- just watch the cursor), it does 2 hearts of damage and stuns the enemy for a short time. If the enemy is shielding, it pierces through the shield.

*Being able to do slashes as fast as possible is very important -- you should be able to do them as soon as the cursor charges fully.*

[gif 1 -- slash someone without shield] 

[gif 2 -- slash someone with shield] 

**Double slash** -- charged double attack (it takes 1 and 1/4 of a second to charge it, again, watch the cursor), does 4 hearts in total (if unshielded). If shielding, the first slash pierces the shield, the second slash deals 2 hearts of damage.

[gif 1 -- double slash without shield] 

[gif 2 -- double slash with shield]

For now you should keep in mind that if you jab the shield, you get stunned for a short while. Avoid doing it, because you can get jabbed during that moment, or in some cases even slashed:

[gif 1 -- jab shield, get jabbed]

[gif 2 -- jab shield, get slashed]

You can also **slide on your shield** (hold W and shield down):

[gif 1 -- shield slide]

**Shield stun** -- If you quickly shield slide into someone, he can also get stunned for a short time (and sometimes knocked back):

[gif 1 -- shield slide into someone to stun]

**Glide** -- use the shield as a parachute:

[gif 1 -- shield parachute]

Not really a knight-only move, but you can also stomp the enemy if you fall on him with enough momentum.

[gif 1 -- stomp 1 heart]
[gif 2 -- stomp shield]
[gif 3 -- stomp 2 heart]

---

Of course, you can do much more with these moves -- you could chain combos, for example slashing someone and then quickly jabbing him after, but you'll learn about that later on. For now, it's just important to know the theory as to how the combat works. The one thing you should focus on related to combat is to mostly use slashes for now -- the most common mistake a newbie can do is just jab spam, which is easily counterable and can quickly get you killed.

---

## Items

There are various knight-specific items, such as bombs and waterbombs, which can be bought at the knight workshop in CTF (25 coins), trader shop in TDM (20 coins) or generated by explosives factories in TTH.

**Bombs** in your inventory can be activated with the spacebar button. It takes 4 seconds before a bomb explodes. You can throw bombs near enemies to damage them (the damage depends on how close the bomb was -- 3 hearts or 1,5 hearts), or use it to bomb jump.

[gif 1 -- throw bomb at enemies]

[gif 2 -- bomb jump]

Keep in mind that if you throw the bomb too early the enemies can catch it and throw it back.

[gif 1 -- throw back bomb]

Then there's a **waterbomb**, which explodes on impact and stuns you for a bit. If you shield it, it stuns you for slightly shorter time. You can also put a sponge in your inventory (bought at TDM trader shop or CTF builder shop) which will also reduce the stun duration. If you successfully stun someone with it, you could for example kill him with a double slash.

[gif 1 -- water bomb without shield]

[gif 2 -- water bomb with shield]

[gif 3 -- water bomb with sponge]
^ The stunned person had a sponge in the inventory.

[gif 4 -- slashing someone while hes stunned]

There's also a **mine** (60 coins in CTF knight shop, but the mine can actually be used by every class), which activates if it stays still on the ground for some time. It instakills enemies and you can't shield it, so you should watch out for enemy mines!

[gif 1 -- mine activating and players dying to mine]

The last item is a **keg** (120 coins in CTF knight shop), which is a powerful (also unshieldable) explosive item with a 6 seconds fuse. You should avoid fighting enemies while holding a keg (you can't put it in your inventory) because they may steal it and hurt your team (one of the most common mistakes that can be made). Generally, you should activate kegs in the middle of the enemy base or next to the enemy flag room.

[gif 1 -- keg exploding in the middle of enemy base]

[gif 2 -- player losing a keg to the enemies]

## Movement
One of the most important things to learn when you're starting to play KAG is how to navigate the terrain properly: if you don't feel your character and its movement, you will have trouble slashing your enemies from a distance or even avoiding enemy attacks. You have to be able to move around obstacles freely, consistently use walljumps, use your slash to gain additional momentum or jump forward while slashing to quickly move through terrain.

[gif 1 -- walljump]

[gif 2 -- slash giving momentum]

[gif 3 -- jumping forward while slashing]

There's not really much to explain here -- it just takes practice, but if you really want to get better faster, then you just could play Save the Princess or the solo Challenges modes.

## Getting good
Every time you die to someone, ask yourself the question -- why did I die? Could I've done something to avoid death? Did I mess up timing or get baited by the enemy? Try to learn on your mistakes and minimize them as much as possible:

[gif 1 -- slashing at someone while he already started slashing]

[gif 2 -- messing up a slash jump at someone]

[gif 3 -- jabbing a shield]

Remember to slash often -- if you constantly slash, the enemies will be afraid to get closer to you. Make use of double slashes as well -- the first slash pierces through the shield and the second one deals 2 hearts of damage, as mentioned earlier.

[gif 1 -- slashing and holding ground so the enemy doesn't get close]

[gif 2 -- double slashing an enemy that retreats with a shield]

Don't get demotivated if you're not as good as you want to be -- as we said earlier, at this level you just need to practice a lot and skill will come with time. Most of the players get stuck at what this guide considers the *average* level. The next chapters should help you getting past that point.
