# Miscellanous - Tick Table

## Tick Table

30 ticks = 1 second.

Important note: Most (if not all) stuns do not add up.

| Action | Number of ticks |
|:----------------------------------------------------| ------------------:|
| Slash charging takes:                               | 15 ticks.          |
| Double slash charging takes:                        | 38 ticks.          |
| Charging limit is reached at:                       | 63 ticks.          |
| Slash duration is:                                  | 13 ticks.          |
| Double slash duration is:                           | 8 + 13 (21) ticks. |
| Stab duration is:                                   | 9 ticks.           |
| Resheathing (prevents shield / sword use) takes:    | 2 ticks.           |
| Overcharging (archer and knight) stuns for:         | 15 ticks.          |
| Mine activation takes:                              | 45 ticks.          |
| Bomb activation takes:                              | 120 ticks.         |
| Keg activation takes:                               | 180 ticks.         |
| Slashes (clean hit) stuns for:                      | 20 ticks.          |
| Slashes (shielded) stuns (enemy) for:               | 10 ticks.          |
| Stabs (clean hit) stuns for:                        | 2 ticks.           |
| Stabs (shielded) stuns (enemy) for:                 | 0 ticks.           |
| Stabs (shielded) stuns (yourself) for:              | 30 ticks.          |
| Shield bash stuns for:                              | 20 ticks.          |
| Stomps stuns for:                                   | 15 ticks.          |
| Bombs (clean hit) stuns for:                        | 20 ticks.          |
| Bombs (shielded) stuns for:                         | 20 ticks.          |
| Arrows (real close) stuns for:                      | 20 ticks.          |
| Arrows (clean hit) stuns for:                       | 15 or 0 ticks. (15 if shot from a close distance) |
| Arrows (shielded) stuns for:                        | 15 or 0 ticks. (15 if shot from a close distance) |
| Spikes stuns for:                                   | 10 ticks.          |
| Getting hit in bed stuns for:                       | 30 ticks.          |
| Travel via tunnel stuns for:                        | 30 ticks.          |
| Water stuns for:                                    | 45 ticks.          |
| Water (w/ sponge) stuns for:                        | 5 ticks.           |
| Getting shot w/ catapult stuns for:                 | 30 ticks.          |
| Falling stuns for:                                  | 12 ticks.          |

## Videos

Some videos of 1v1s I did -- try to analyse and understand what is happening on the screen; pay attention to tricks such as instaslashes, instajabs, slash stomps, shieldbashes, etc. Try to notice mistakes that I make and what causes my death. 

1v1 Bunnie vs Blackiceball https://www.youtube.com/watch?v=ZSfmCd5ZKoY
1v1 Bunnie vs Eshlost https://www.youtube.com/watch?v=6MVQPdZmWyw
1v1 Bunnie vs frangeorgeelliott https://www.youtube.com/watch?v=ZzP4XXEaP3Q
1v1 Bunnie vs Junko-Enoshima https://www.youtube.com/watch?v=Cfoq16YZYtM

## TDM vs CTF fall damage

CTF has much more strict fall damage than TDM. Keep this in mind when jumping off from your tower or doing slash stomps from big distances. 

Some numbers (without gliding):

stun from falling (no damage) on TDM: from 17 blocks minimum
stun from falling (no damage) on CTF: from 12 blocks minimum

stun from falling with 0.5 heart of damage on TDM: from 23 blocks minimum
stun from falling with 0.5 heart of damage on CTF: from 17 blocks minimum

stun from falling with 1 heart of damage on TDM: from 33 blocks minimum
stun from falling with 1 heart of damage on CTF: from 23 blocks minimum

stun from falling with 4 hearts of damage on TDM: from 48 blocks minimum
stun from falling with 4 hearts of damage on CTF: from 33 blocks minimum



